version: '2.28.1'

services:
  database:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blogs
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogspost
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  blogposts:
    image: blogposts:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=p1
      - spring.data.redis.host=redis
      - spring.data.redis.port=6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/blogspost
      - SPRING_DATASOURCE_USERNAME=blogs
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_LIQUIBASE_CHANGELOG=classpath:db/changelog/db.changelog-master.yaml
      - SPRING_LIQUIBASE_ENABLED=true
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_APACHE_COYOTE=DEBUG
      - LOGGING_LEVEL_ORG_APACHE_TOMCAT_UTIL_NET=DEBUG
      - SECURITY_JWT_EXPIRATION_MINUTES=30
      - SECURITY_JWT_REFRESH_TOKEN_DURATION_MS=1800000
      - SECURITY_JWT_SECRET_KEY=MN4DSNQUtkokVfqSsK3ALYCarer6TRrhgsXms9UXoeA=
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
    depends_on:
      - redis
      - database
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
