version: '2.28.1'

services:
  database:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: blogspost
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  blogposts:
    image: blogposts:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - spring.data.redis.host=${REDIS_HOST}
      - spring.data.redis.port=${REDIS_PORT}
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_LIQUIBASE_CHANGELOG=classpath:db/changelog/db.changelog-master.yaml
      - SPRING_LIQUIBASE_ENABLED=true
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_APACHE_COYOTE=DEBUG
      - LOGGING_LEVEL_ORG_APACHE_TOMCAT_UTIL_NET=DEBUG
      - SECURITY_JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
      - SECURITY_JWT_REFRESH_TOKEN_DURATION_MS=${JWT_REFRESH_TOKEN_DURATION_MS}
      - SECURITY_JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
    depends_on:
      - redis
      - database
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
