package blog.posts.p1.authentication.userManagement.enums;

public enum PermissionEnum {
//    PROVIDER PERMISSIONS
    CREATE_PRODUCT,
    SELL_OWN_PRODUCT,
    DELETE_OWN_PRODUCT,
    READ_OWN_PRODUCTS,
    EDIT_OWN_PRODUCT,

//    ADMIN PERMISSIONS
    CREATE_ACCOUNTS,
    EDIT_ACCOUNTS,
    DELETE_ACCOUNTS,
    CHANGE_USER_ROLE,
    CHANGE_PERMISSIONS,
    DELETE_PRODUCTS,

    // CLIENT PERMISSIONS
    BUY_PRODUCT,
    CANCEL_PURCHASE,

    // CLIENT/ADMIN PERMISSIONS
    MAKE_PAYMENT,
    READ_ALL_PRODUCTS,

    // ALL
    DELETE_OWN_ACCOUNT



}
